{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: dns-egress
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: 
        - "53"
        {{- if .Values.openshift }}
        - "5353"
        {{- end }}
{{- end }}
