{{- if and ( .Values.istio.enabled ) ( .Values.istio.renovate.enabled ) }}
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default-renovate"
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode | default "PERMISSIVE" }}
{{ end }}